# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: en
title: HeresTomWithTheWeather
email: herestomwiththeweather@gmail.com
description: Mostly about Internet and ice hockey
permalink: pretty
# Webmentions - leave blank (remove "yes") if you would not like to receive & display webmentions from other sites
webmentions: yes

include: ['/.well-known']
exclude:
  - vendor

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://herestomwiththeweather.com" # the base hostname & protocol for your site
twitter_username: tomwiththeweath
github_username: herestomwiththeweather
flickr_username: tbbrown
goodreads_username: 656838-tom-brown
keybase_username: tbbrown

# Can be over ridden with author: in Front Matter
author: Tom

# Expecting a full url, not relative to site.url
author_img: https://stark-moon-46.s3.amazonaws.com/images/16299.jpg

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist

paginate: 5
post:
  template: _post.txt
  extension: markdown
